version: '2.0'

services:
    app:
      build: .
      network: host
      ports:
      - "65282:65282/udp"
      volumes:
      - "/sys/class/backlight/rpi_backlight/:/sys/class/backlight/rpi_backlight/"
      privileged: true
